name: Release
on: 
  release:
         types: ['published']
jobs:

  build-and-publish-images:
    name: Build and publish publish-sbom image
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: yewnorosen
          password: ${{ secrets.YEWNOROSEN_DOCKERHUB_PUSH }}
      - name: checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Build and push publish-sbom
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: yewnorosen/publish-sbom:latest
  
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0.3.0
        with:
          image: yewnorosen/publish-sbom:latest
          format: cyclonedx
          
  publish-sbom:
    name: Publish SBOM to RKVST
    runs-on: ubuntu-latest
    steps:
       - uses: actions/download-artifact@v2
       - uses: leflambeur/publish-sbom@v0.0.2
         env:
           CLIENT_ID: ${{ secrets.CLIENT_ID }}
           SECRET: ${{ secrets.CLIENT_SECRET }}
         with:
           url: https://qa.wild.jitsuin.io
           sbom-files: "yewnorosen-rkvst-sbom_latest.cyclonedx/yewnorosen-rkvst-sbom_latest.cyclonedx"
